In [123]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [124]:
# Series
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [125]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [126]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [127]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [128]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [129]:
obj2['a']

np.int64(-5)

In [130]:
obj2['d'] = 6

In [131]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [132]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [133]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [134]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [135]:
"b" in obj2

True

In [136]:
"e" in obj2

False

In [137]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [138]:
obj3 = pd.Series(sdata)

In [139]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [140]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [141]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [142]:
obj4 = pd.Series(sdata, index=states)

In [143]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [144]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [145]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [146]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [147]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [148]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [149]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [150]:
obj4.name = 'population'
obj4.index.name = 'state'

In [151]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [152]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [153]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [154]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [155]:
# DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)

In [156]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [157]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [158]:
frame.tail()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [159]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [160]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five'])

In [161]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [162]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [163]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [164]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [165]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [166]:
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [167]:
frame2['debt'] = 16.5

In [168]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [169]:
frame2['debt'] = np.arange(5.)

In [170]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [171]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [172]:
frame2['debt'] = val

In [173]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [174]:
frame2['eastern'] = frame2.state == 'Ohio'

In [175]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [176]:
del frame2['eastern']

In [177]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [178]:
populations = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [179]:
frame3 = pd.DataFrame(populations)

In [180]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [181]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [182]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [183]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [184]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [185]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [186]:
frame3.to_numpy()

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [187]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [188]:
# Index objects
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [189]:
index = obj.index

In [190]:
index

Index(['a', 'b', 'c'], dtype='object')

In [191]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [192]:
labels = pd.Index(np.arange(3))

In [193]:
labels

Index([0, 1, 2], dtype='int64')

In [194]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [195]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [196]:
obj2.index is labels

True

In [197]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [198]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [199]:
'Ohio' in frame3.columns

True

In [200]:
2003 in frame3.index

False

In [201]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [202]:
# Essential functionality
# Reindexing
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [203]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [204]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [205]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [206]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [207]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [208]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [209]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [210]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [211]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [212]:
states = ['Texas', 'Utah', 'California']

In [213]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [214]:
frame.reindex(states, axis='columns')

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [215]:
# Dropping entries from an axis
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [216]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [217]:
new_obj = obj.drop('c')

In [218]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [219]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [220]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [221]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [222]:
data.drop(index=['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [223]:
data.drop(columns=['two'])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [224]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [225]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [226]:
# Indexing, selection, and filtering
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [227]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [228]:
obj['b']

np.float64(1.0)

In [229]:
obj.iloc[1]

np.float64(1.0)

In [230]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [231]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [232]:
obj.iloc[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [233]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [234]:
obj.loc[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [235]:
obj1= pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1 ,2 , 3], index=['a', 'b', 'c'])

In [236]:
obj1

2    1
0    2
1    3
dtype: int64

In [237]:
obj2

a    1
b    2
c    3
dtype: int64

In [238]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [239]:
obj2.loc[[0 ,1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [240]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [241]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [242]:
obj2.loc['b':'c'] =5

In [243]:
obj2

a    1
b    5
c    5
dtype: int64

In [244]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [245]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [246]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [247]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [248]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [249]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [250]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [251]:
data[data < 5] = 0

In [252]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [253]:
# Selection with loc and iloc
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [254]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [257]:
data.loc[['Colorado','New York']]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [258]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [259]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [260]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [261]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [262]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [263]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [264]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [265]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [266]:
# Integer indexes
ser = pd.Series(np.arange(3.))

In [267]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [268]:
ser[-1]

KeyError: -1

In [269]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [270]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [272]:
ser2.iloc[-1]

np.float64(2.0)

In [273]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [274]:
data.loc[:,'one'] =1

In [275]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [276]:
data.iloc[2] =5

In [277]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [278]:
data.loc[data['four'] > 5] =3

In [279]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [280]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [281]:
data.loc[data.three ==5 , 'three'] = 6

In [282]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [283]:
# Arithmetic and data alignment
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [284]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [285]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [286]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [289]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bce'),
                   index=['Utah', 'Ohio', 'Texas','Oregon'])


In [290]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [291]:
df2

b     c     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [292]:
df1 + df2

b     c   d   e
Colorado  NaN   NaN NaN NaN
Ohio      3.0   5.0 NaN NaN
Oregon    NaN   NaN NaN NaN
Texas     9.0  11.0 NaN NaN
Utah      NaN   NaN NaN NaN

In [293]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [294]:
df1

A
0  1
1  2

In [295]:
df2

B
0  3
1  4

In [296]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [297]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [298]:
df2.loc[1, 'b'] = np.nan

In [299]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [300]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [301]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [302]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [303]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [304]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [305]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [306]:
# Operations between DataFrame and Series
arr = np.arange(12.).reshape((3, 4))

In [307]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [308]:
arr[0]

array([0., 1., 2., 3.])

In [309]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [310]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [311]:
series = frame.iloc[0]

In [312]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [313]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [314]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [315]:
series2 = pd.Series(np.arange(3), index=['b', 'e', 'f'])

In [316]:
series2

b    0
e    1
f    2
dtype: int64

In [317]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [318]:
series3 = frame['d']

In [319]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [320]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [321]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0