In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
# Series
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

np.int64(-5)

In [8]:
obj2['d'] = 6

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
"b" in obj2

True

In [14]:
"e" in obj2

False

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [16]:
obj3 = pd.Series(sdata)

In [17]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [20]:
obj4 = pd.Series(sdata, index=states)

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [28]:
obj4.name = 'population'
obj4.index.name = 'state'

In [29]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [32]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [33]:
# DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
frame.tail()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [37]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [38]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five'])

In [39]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [43]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [44]:
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [45]:
frame2['debt'] = 16.5

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [47]:
frame2['debt'] = np.arange(5.)

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [49]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'

In [53]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [54]:
del frame2['eastern']

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
populations = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [57]:
frame3 = pd.DataFrame(populations)

In [58]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [59]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [60]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [62]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [63]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [64]:
frame3.to_numpy()

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [65]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [66]:
# Index objects
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [67]:
index = obj.index

In [68]:
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [70]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

NameError: name 'labels' is not defined

In [71]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [72]:
obj2.index is labels

NameError: name 'labels' is not defined

In [73]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [74]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [75]:
'Ohio' in frame3.columns

True

In [76]:
2003 in frame3.index

False

In [77]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [78]:
# Essential functionality
# Reindexing
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [79]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [80]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [81]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [82]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [83]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [84]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [85]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [86]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [87]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [88]:
states = ['Texas', 'Utah', 'California']

In [89]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [90]:
frame.reindex(states, axis='columns')

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [91]:
# Dropping entries from an axis
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [92]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [93]:
new_obj = obj.drop('c')

In [94]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [95]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [96]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [97]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data.drop(index=['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop(columns=['two'])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [100]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [101]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [102]:
# Indexing, selection, and filtering
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [103]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [104]:
obj['b']

np.float64(1.0)

In [105]:
obj.iloc[1]

np.float64(1.0)

In [106]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [107]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [108]:
obj.iloc[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [109]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [110]:
obj.loc[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [111]:
obj1= pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1 ,2 , 3], index=['a', 'b', 'c'])

In [112]:
obj1

2    1
0    2
1    3
dtype: int64

In [113]:
obj2

a    1
b    2
c    3
dtype: int64

In [114]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [115]:
obj2.loc[[0 ,1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [116]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [117]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [118]:
obj2.loc['b':'c'] =5

In [119]:
obj2

a    1
b    5
c    5
dtype: int64

In [120]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [121]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [123]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [124]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [125]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [126]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [127]:
data[data < 5] = 0

In [128]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
# Selection with loc and iloc
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [131]:
data.loc[['Colorado','New York']]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [132]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [133]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [134]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [135]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [136]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [137]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [138]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [139]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
# Integer indexes
ser = pd.Series(np.arange(3.))

In [141]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [142]:
ser[-1]

KeyError: -1

In [ ]:
ser

In [143]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [144]:
ser2.iloc[-1]

np.float64(2.0)

In [145]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [146]:
data.loc[:,'one'] =1

In [147]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [148]:
data.iloc[2] =5

In [149]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [150]:
data.loc[data['four'] > 5] =3

In [151]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [152]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [153]:
data.loc[data.three ==5 , 'three'] = 6

In [154]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [155]:
# Arithmetic and data alignment
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [156]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [157]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [158]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [159]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bce'),
                   index=['Utah', 'Ohio', 'Texas','Oregon'])


In [160]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [161]:
df2

b     c     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [162]:
df1 + df2

b     c   d   e
Colorado  NaN   NaN NaN NaN
Ohio      3.0   5.0 NaN NaN
Oregon    NaN   NaN NaN NaN
Texas     9.0  11.0 NaN NaN
Utah      NaN   NaN NaN NaN

In [163]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [164]:
df1

A
0  1
1  2

In [165]:
df2

B
0  3
1  4

In [166]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [167]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [168]:
df2.loc[1, 'b'] = np.nan

In [169]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [170]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [171]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [172]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [173]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [174]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [175]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [176]:
# Operations between DataFrame and Series
arr = np.arange(12.).reshape((3, 4))

In [177]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [178]:
arr[0]

array([0., 1., 2., 3.])

In [179]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [180]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [181]:
series = frame.iloc[0]

In [182]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [183]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [184]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [185]:
series2 = pd.Series(np.arange(3), index=['b', 'e', 'f'])

In [186]:
series2

b    0
e    1
f    2
dtype: int64

In [187]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [188]:
series3 = frame['d']

In [189]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [190]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [191]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [193]:
# Function application and mapping
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [194]:
frame

b         d         e
Utah    0.149302 -1.543772  1.166022
Ohio   -1.225399 -0.089692  1.930084
Texas  -0.364542 -0.800014 -0.744644
Oregon -0.123832 -0.207682 -0.581578

In [195]:
np.abs(frame)

b         d         e
Utah    0.149302  1.543772  1.166022
Ohio    1.225399  0.089692  1.930084
Texas   0.364542  0.800014  0.744644
Oregon  0.123832  0.207682  0.581578

In [196]:
def f1(x):
    return x.max()- x.min()

In [197]:
frame.apply(f1)

b    1.374701
d    1.454080
e    2.674728
dtype: float64

In [198]:
frame.apply(f1, axis='columns')

Utah      2.709794
Ohio      3.155483
Texas     0.435472
Oregon    0.457747
dtype: float64

In [199]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [200]:
frame.apply(f2)

b         d         e
min -1.225399 -1.543772 -0.744644
max  0.149302 -0.089692  1.930084

In [201]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [202]:
frame.apply(f2)

b         d         e
min -1.225399 -1.543772 -0.744644
max  0.149302 -0.089692  1.930084

In [203]:
def my_format(x):
    return f"{x:.2f}"

In [205]:
frame.map(my_format)

b      d      e
Utah     0.15  -1.54   1.17
Ohio    -1.23  -0.09   1.93
Texas   -0.36  -0.80  -0.74
Oregon  -0.12  -0.21  -0.58

In [206]:
frame["e"].map(my_format)

Utah       1.17
Ohio       1.93
Texas     -0.74
Oregon    -0.58
Name: e, dtype: object

In [207]:
# Sorting and ranking
obj= pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [208]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [209]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [210]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [211]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [212]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [213]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [214]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [215]:
obj = pd.Series([4, 7, -3, 2])

In [216]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [217]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [218]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [219]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [220]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [221]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [222]:
frame.sort_values('b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [223]:
frame.sort_values(['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [224]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [225]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [226]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [228]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [229]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],  'c': [-2, 5, 8, -2.5]})

In [230]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [231]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [232]:
# Axis indexes with duplicate labels
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [233]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [234]:
obj.index.is_unique

False

In [235]:
obj['a']

a    0
a    1
dtype: int64

In [236]:
obj['c']

np.int64(4)

In [237]:
df = pd.DataFrame(np.random.standard_normal((5 ,3)), index=['a', 'a', 'b', 'b', 'c'])

In [238]:
df

0         1         2
a  0.633144  0.226881  1.093103
a -0.128318  0.184100  0.023149
b -0.257087 -0.586948 -0.665914
b  0.130452 -0.471018 -2.144371
c  1.044602  0.066430  0.908268

In [239]:
df.loc['b']

0         1         2
b -0.257087 -0.586948 -0.665914
b  0.130452 -0.471018 -2.144371

In [240]:
df.loc['c']

0    1.044602
1    0.066430
2    0.908268
Name: c, dtype: float64

In [241]:
# Summarizing and computing descriptive statistics
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [242]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [243]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [244]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [246]:
df.mean(axis='index', skipna=False)

one   NaN
two   NaN
dtype: float64

In [247]:
df.sum(axis='index', skipna=False)

one   NaN
two   NaN
dtype: float64

In [248]:
df.sum(axis='columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [249]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [250]:
df.idxmax()

one    b
two    d
dtype: object

In [251]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [252]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [253]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [254]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [256]:
# Correlation and covariance
price = pd.read_pickle("examples/yahoo_price.pkl")
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [257]:
returns = price.pct_change()

In [258]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [259]:
returns['MSFT'].corr(returns['IBM'])

np.float64(0.49976361144151144)

In [260]:
returns['MSFT'].cov(returns['IBM'])

np.float64(8.870655479703546e-05)

In [261]:
returns['MSFT'].corr(returns['IBM'])

np.float64(0.49976361144151144)

In [262]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [263]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [264]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [265]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [266]:
# Unique values, value counts, and membership
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [267]:
uniques = obj.unique()

In [268]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [269]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [271]:
pd.Series.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [272]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [273]:
mask = obj.isin(['b', 'c'])

In [274]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [275]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [276]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [277]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [278]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [279]:
indices

array([0, 2, 1, 1, 0, 2])

In [280]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [281]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [282]:
data['Qu1'].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [285]:
result = data.apply(lambda x: pd.Series(x).value_counts()).fillna(0)

In [286]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [287]:
data = pd.DataFrame({'a': [1, 1, 1,2 , 2], 'b': [0, 0, 1, 0, 0]})

In [288]:
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [289]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64